import type { AuditRun } from "./types";
import { countByImpact, scoreLabel } from "./score";

export function buildMarkdownReport(run: AuditRun): string {
  const counts = countByImpact(run.violations);
  const lines: string[] = [];

  lines.push(`# AccessLens report`);
  lines.push("");
  lines.push(`Ran: ${run.ranAt}`);
  lines.push(`Score: **${run.score} / 100** (${scoreLabel(run.score)})`);
  lines.push("");
  lines.push(
    `| Critical | Serious | Moderate | Minor |\n|---|---|---|---|\n| ${counts.critical} | ${counts.serious} | ${counts.moderate} | ${counts.minor} |`
  );
  lines.push("");

  if (run.violations.length === 0) {
    lines.push("No violations detected by axe-core's ruleset.");
  } else {
    lines.push("## Violations");
    lines.push("");
    for (const v of run.violations) {
      lines.push(`### ${v.help} (${v.impact ?? "unknown"})`);
      lines.push("");
      lines.push(v.description);
      lines.push("");
      lines.push(`Rule: \`${v.id}\` — [details](${v.helpUrl})`);
      lines.push("");
      for (const node of v.nodes) {
        lines.push(`- \`${node.target.join(" ")}\``);
        if (node.failureSummary) {
          lines.push(`  - ${node.failureSummary.replace(/\n/g, " ")}`);
        }
      }
      lines.push("");
    }
  }

  if (run.altTextSuggestions.length > 0) {
    lines.push("## Suggested alt text");
    lines.push("");
    lines.push("| Image | Suggested alt | Source |");
    lines.push("|---|---|---|");
    for (const s of run.altTextSuggestions) {
      lines.push(
        `| \`${s.selector}\` | ${s.suggestedAlt} | ${
          s.source === "ai" ? "AI-suggested — verify" : "heuristic"
        } |`
      );
    }
    lines.push("");
  }

  lines.push("---");
  lines.push(
    "_Generated by AccessLens. Findings come from axe-core's automated ruleset, which catches roughly 30–50% of WCAG issues — always pair with manual review and testing with real assistive technology._"
  );

  return lines.join("\n");
}

export function downloadMarkdown(filename: string, content: string) {
  const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
